remote_theme: https://github.com/academicpages/academicpages.github.io
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one




# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Bentelega / Core"
title_separator          : "-"
name                     : &name "BenTelegaCore"
description              : &description "Your Name's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
